letterpad/editor

yarn.lock

**Preview Url**: https://deploy-preview-[ENTER-PR-NUMBER-FROM-URL]--letterpad-editor.netlify.com/

fix: yarn.lock integrity sha

---

postcss.config.js
src/plugins/linebreak/LinebreakButton.js
src/plugins/linebreak/LinebreakKeyboardShortcut.js
src/plugins/linebreak/LinebreakUtils.js
src/plugins/markdown/MarkdownKeyboardShortcut.js
src/plugins/markdown/MarkdownUtils.js
src/plugins/markdown/index.js
src/plugins/markdown/match/blockquote.js
src/plugins/markdown/match/bold.js
src/plugins/markdown/match/boldItalic.js
src/plugins/markdown/match/code.js
src/plugins/markdown/match/codeBlock.js
src/plugins/markdown/match/header.js
src/plugins/markdown/match/hr.js
src/plugins/markdown/match/image.js
src/plugins/markdown/match/italic.js
src/plugins/markdown/match/link.js

**Preview Url**: https://deploy-preview-[ENTER-PR-NUMBER-FROM-URL]--letterpad-editor.netlify.com/

format all fileswith prettier

---

.travis.yml

**Preview Url**: https://deploy-preview-[ENTER-PR-NUMBER-FROM-URL]--letterpad-editor.netlify.com/

fix: remove node 8 from travis

---

src/components/Toolbar.tsx
src/editor.tsx
src/plugins/audio/AudioButton.tsx
src/plugins/audio/AudioInput.tsx
src/plugins/audio/AudioUtils.ts
src/plugins/audio/index.tsx
src/plugins/index.ts

**Preview Url**: https://deploy-preview-[ENTER-PR-NUMBER-FROM-URL]--letterpad-editor.netlify.com/

feat: placeholder for toolbar input

---

e2e/tests/__snapshots__/menubar-actions.ts.snap
e2e/tests/__snapshots__/toolbar-actions.ts.snap
e2e/tests/toolbar-actions.ts
src/plugins/index.ts
src/plugins/pluginConfigs.ts
src/plugins/video/VideoButton.tsx
src/plugins/video/VideoInput.tsx
src/plugins/video/VideoNode.tsx
src/plugins/video/VideoUtils.ts
src/plugins/video/index.tsx
src/plugins/youtube/YoutubeUtils.ts

Replaced youtube with video which can recognise both youtube and vimeo links

Video enhancement

---

src/components/Toolbar.tsx
src/editor.tsx
src/plugins/link/index.tsx
src/plugins/paragraph/index.tsx

fix paragraph pasting

---

examples/demo-1/index.tsx
index.html
src/editor.css.ts
src/editor.tsx
src/plugins/image/ImageNode.tsx

stylize editor spacing and fix image

---

src/plugins/link/index.tsx

fixed markdown for link

---

e2e/tests/__snapshots__/toolbar-actions.ts.snap
examples/demo-1/index.tsx
index.html
src/components/Toolbar.tsx
src/editor.css.ts
src/editor.tsx
src/helper/schema.ts
src/plugins/blockquote/BlockquoteNode.tsx
src/plugins/codeblock/CodeblockNode.tsx
src/plugins/gallery/GalleryNode.css.ts
src/plugins/highlight/HighlightMark.tsx
src/plugins/linebreak/LinebreakNode.js
src/plugins/linebreak/LinebreakUtils.ts
src/plugins/link/LinkNode.tsx
src/theme.css.ts
src/themes/dark.css.ts
src/themes/index.ts
src/themes/light.css.ts

Feature - Adding themes

---

src/editor.tsx
src/plugins/audio/index.tsx
src/plugins/autoscroll/index.ts
src/plugins/blockquote/index.tsx
src/plugins/bold/index.tsx
src/plugins/codeblock/index.tsx
src/plugins/embed/index.tsx
src/plugins/gallery/index.tsx
src/plugins/headings/index.tsx
src/plugins/highlight/index.tsx
src/plugins/image/index.tsx
src/plugins/index.ts
src/plugins/italic/index.tsx
src/plugins/linebreak/index.tsx
src/plugins/link/index.tsx
src/plugins/list/index.tsx
src/plugins/paragraph/index.tsx
src/plugins/underline/index.tsx
src/value.ts

Rename the plugin config file property.

Rename plugin tag

---

index.html
src/plugins/embed/EmbedGist.tsx
src/plugins/embed/EmbedNode.tsx
src/plugins/embed/EmbedUtils.ts
src/value.ts

Embed Gist

---

src/plugins/codeblock/CodeblockNode.tsx
src/plugins/codeblock/index.tsx
src/plugins/gallery/GalleryNode.css.ts
src/plugins/gallery/GalleryNode.tsx
src/plugins/image/ImageNode.css.ts

Fixed scroll movements in gallery

---

examples/demo-1/Gallery.tsx
package.json
src/components/Toolbar.tsx
src/helper/scrollToCursor.ts
src/helper/showMenu.ts
src/plugins/audio/AudioInput.tsx
src/plugins/autoscroll/scrollToCursor.tsx
src/plugins/codeblock/CodeblockKeyboardShortcut.tsx
src/plugins/codeblock/CodeblockUtils.tsx
src/plugins/embed/EmbedInput.tsx
src/plugins/image/ImageInput.tsx
yarn.lock

Typescript fixes

---

cypress/integration/list.spec.js
index.html
package.json
snapshots.js
src/plugins/list/ListKeyboardShortcut.ts
src/plugins/list/index.tsx

fix: remove nested lists

---

.circleci/config.yml
package.json
src/editor.tsx
src/plugins/index.ts
src/typings/styled-components.d.ts
yarn.lock

NPM publishing scripts

---

.circleci/config.yml
Readme.md
package.json
scripts/e2e.sh
src/editor.css.ts
src/editor.tsx

Chor Update - Comments, Default props and cosmetics

---

src/components/Button.tsx
src/editor.css.ts
src/plugins/giphy/GiphyButton.tsx
src/plugins/headings/HeadingsButton.tsx
src/plugins/index.ts

Fixed toolbar button text

---

src/components/Button.tsx
src/editor.css.ts
src/plugins/giphy/GiphyButton.tsx
src/plugins/headings/HeadingsButton.tsx
src/plugins/index.ts

Allow text in toolbar button icons

---

.circleci/config.yml

add umd to workspace for publish

---

examples/demo-1/index.tsx
index.html
src/initialText.md
src/themes/base.css

Body: Lora
Headings: Montserrat

feat: change default font of editor to Lora and Montserrat

---

package.json
src/components/Code.tsx
src/themes/base.css
yarn.lock

Added external code css

---

src/components/BlockInsert.tsx

Use functional components state, effects and refs for block insert

refactor: block insert to functional component

---

Readme.md
src/components/BlockInsert.tsx
src/components/CheckListItem.tsx
src/components/EmbedProviders/index.ts
src/components/Frame.tsx
src/components/HorizontalRule.tsx
src/components/HoveringMenu.tsx
src/components/Image.tsx
src/components/LinkToolbar.tsx
src/components/Placeholder.ts
src/editor.tsx
src/themes/base.css
test-utils/server.js

fix the deploy bug and replace classnames in css

---

package.json

remove react embed

---

CHANGELOG.md
package.json
src/components/Code.tsx
src/mdToHtml.tsx
src/plugins/Embeds.tsx
src/themes/base.css

Css fixes and add image caption in html

---

CHANGELOG.md
examples/demo-1/index.tsx
package.json
snapshots.js
src/components/BlockToolbar.tsx
src/components/FormattingToolbar.tsx
src/components/LinkToolbar.tsx
src/components/ToolbarButton.tsx
src/editor.tsx
src/plugins/Embeds.tsx
yarn.lock

Add tooltip icons

---

CHANGELOG.md
package.json
src/editor.tsx
src/plugins/Embeds.tsx

Add onload callback

---

CHANGELOG.md
cypress/integration/menu.spec.js
cypress/support/index.js
package.json
scripts/release.sh
snapshots.js
tsconfig.compiler.json
yarn.lock

Convert build to commonjs instead f module
